### ISSUE TITLE
TypeError: EndVector() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by HL2222** [meilof/pysnark#21]
hello , i use the "To generate a zkif file for the zkinterface bulletproofs backend and use it:" when i input the command "PYSNARK_BACKEND=zkifbulletproofs python3 cube.py 33"，i encountered the following problem：

```
(newpysnark36) ➜  examples git:(master) PYSNARK_BACKEND=zkifbulletproofs python3 cube.py 33
The cube of 33 is 35937
*** zkinterface: writing circuit
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/Users/liuhuan/opt/anaconda3/envs/newpysnark36/lib/python3.6/site-packages/pysnark/atexitmaybe.py", line 57, in maybe_
    fn()
  File "/Users/liuhuan/opt/anaconda3/envs/newpysnark36/lib/python3.6/site-packages/pysnark/runtime.py", line 688, in final
    if autoprove: backend.prove()
  File "/Users/liuhuan/opt/anaconda3/envs/newpysnark36/lib/python3.6/site-packages/pysnark/zkinterface/backend.py", line 104, in prove
    vars = write_varlist(builder, pubvals, 1)
  File "/Users/liuhuan/opt/anaconda3/envs/newpysnark36/lib/python3.6/site-packages/pysnark/zkinterface/backend.py", line 78, in write_varlist
    ixs = builder.EndVector(len(vals))
TypeError: EndVector() takes 1 positional argument but 2 were given 
```

how do i solve it

**Comment by gxavier38** [comment]
Looks like that was caused by a new version of the Flatbuffers library. See https://github.com/google/flatbuffers/commit/f8b203c9c4bec53cb9abceef6bc333a02f272b6b

@HL2222 In the meantime you could try reinstalling with `pip3 install "flatbuffers<2.0.0"`

**Comment by HL2222** [comment]
Thank you very much. It works .

**Comment by meilof** [comment]
I updated the code, it should now work with the new FlatBuffers
