### ISSUE TITLE
Qapver Error

### ISSUE THREAD

**Issue by iamtrask** [meilof/pysnark#4]
I successfully compiled qaptools and python-libsnark and installed pysnark. However, i can't seem to verify the snark (And i'm not sure it's producing all the files it should)

```
atrask-macbookpro3:examples atrask$ python cube.py 3
The cube of 3 is 27
*** Trying to read pysnark_ek
*** PySNARK: generating proof pysnark_log (sat=True, #io=2, #witness=2, #constraint=3)
*** Public inputs: 3 27
*** Verification status: True
atrask-macbookpro3:examples atrask$ python -m pysnark.qaptools.runqapver
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pysnark/qaptools/runqapver.py", line 60, in <module>
    run()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pysnark/qaptools/runqapver.py", line 55, in run
    raise RuntimeError("qapver failed")
RuntimeError: qapver failed
atrask-macbookpro3:examples atrask$ ls
bench.py			cs2				kaplanmeier.py			snarkprofile.py
binarycircuit.py		cube-qaptools.py		manysquares.py			sudoku.py
binarycircuit_example.txt	cube.py				pysnark_ek			test.py
branch2.py			cube_json.py			pysnark_log			test2.py
compare.py			factorial.py			pysnark_vk			testarray.py
cs				index.html			secretsanta.py			testcomm.py
atrask-macbookpro3:examples atrask$ 
```

**Comment by meilof** [comment]
It seems you are using the libsnark backend to make the proof but using the qapver tool from qaptools to verify. The two backends use different and mutually incompatible sets of files to store the keys and proofs. If you use the libsnark backend (which is the default) then you can use for example snarkjs to verify the proofs (see https://meilof.github.io/pysnark/ <https://meilof.github.io/pysnark/>). You can also use the qaptools backend (e.g., by doing “PYSNARK_BACKEND=qaptools python3 cube.py 33”, in which case the runqapver command you mention should work. But I agree this is not directly clear from the documentation.

Hope that helps!

Op vr 20 dec. 2019 02:49 schreef Andrew Trask <notifications@github.com <mailto:notifications@github.com>>:
I successfully compiled qaptools and python-libsnark and installed pysnark. However, i can't seem to verify the snark (And i'm not sure it's producing all the files it should)

atrask-macbookpro3:examples atrask$ python cube.py 3
The cube of 3 is 27
*** Trying to read pysnark_ek
*** PySNARK: generating proof pysnark_log (sat=True, #io=2, #witness=2, #constraint=3)
*** Public inputs: 3 27
*** Verification status: True
atrask-macbookpro3:examples atrask$ python -m pysnark.qaptools.runqapver
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pysnark/qaptools/runqapver.py", line 60, in <module>
    run()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pysnark/qaptools/runqapver.py", line 55, in run
    raise RuntimeError("qapver failed")
RuntimeError: qapver failed
atrask-macbookpro3:examples atrask$ ls
bench.py			cs2				kaplanmeier.py			snarkprofile.py
binarycircuit.py		cube-qaptools.py		manysquares.py			sudoku.py
binarycircuit_example.txt	cube.py				pysnark_ek			test.py
branch2.py			cube_json.py			pysnark_log			test2.py
compare.py			factorial.py			pysnark_vk			testarray.py
cs				index.html			secretsanta.py			testcomm.py
atrask-macbookpro3:examples atrask$

**Comment by iamtrask** [comment]
Excellent! Thank you so much! I'll let you know how it goes.

Great work on the library by the way.
