### ISSUE TITLE
running example in README.md failed 

### ISSUE THREAD

**Issue by stechu** [meilof/pysnark#7]
Using the latest master source and `snarkjs@0.3.44`:

```
python3 cube.py 33                  
The cube of 33 is 35937
*** Trying to read pysnark_ek
*** No pysnark_ek or computation changed, generating keys...
*** PySNARK: generating proof pysnark_log (sat=True, #io=2, #witness=2, #constraint=3)
*** Public inputs: 33 35937
*** Verification status: True
⋊> ~/P/p/examples on master ◦                                     
⋊> ~/P/p/examples on master ◦                                     
⋊> ~/P/p/examples on master ◦                                     
⋊> ~/P/p/examples on master ◦ python3 -m pysnark.libsnark.tosnarkjs
*** Created proof.json, verification_key.json, public.json; test using "snarkjs verify"

⋊> ~/P/p/examples on master ◦ snarkjs verify                     
[ERROR] snarkJS: TypeError: Cannot read property 'toUpperCase' of undefined
    at normalizeName (/usr/local/lib/node_modules/snarkjs/build/cli.cjs:1703:18)
    at getCurveFromName (/usr/local/lib/node_modules/snarkjs/build/cli.cjs:1692:22)
    at groth16Verify (/usr/local/lib/node_modules/snarkjs/build/cli.cjs:6342:25)
    at Object.groth16Verify$1 [as action] (/usr/local/lib/node_modules/snarkjs/build/cli.cjs:6898:27)
    at clProcessor (/usr/local/lib/node_modules/snarkjs/build/cli.cjs:1264:31)
    at Object.<anonymous> (/usr/local/lib/node_modules/snarkjs/build/cli.cjs:6680:1)
    at Module._compile (internal/modules/cjs/loader.js:1251:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1272:10)
    at Module.load (internal/modules/cjs/loader.js:1100:32)
    at Function.Module._load (internal/modules/cjs/loader.js:962:14)
```

**Comment by meilof** [comment]
That seems to be a problem in snarkjs. Pysnark just generates data for it
to verify. That should not lead to a runtime error. Does snarkjs work on
other examples?

Op ma 26 okt. 2020 23:00 schreef Shumo Chu <notifications@github.com>:

**Comment by stechu** [comment]
snarkjs doesn't work on other examples as well.
I would like to run an end to end example including circuit generation, proving, and verification. is it possible to do so without using snarkjs (I still want the efficiency brought by Groth 16, thus ideally not using QAPTool).

**Comment by meilof** [comment]
This is strange. I just tried with snarkjs@0.3.44 and it works for me. Could you check if snarkjs works with the examples provided with snarkjs itself? Otherwise, could you check whether snarkjs works for you with the attached json files (which were generated by pysnark in my case)? 

What platform are you using? Are you using pysnark from SVN (pip3 install git+https://github.com/meilof/pysnark) or from a release (pip3 install pysnark)?
[Archive.zip](https://github.com/meilof/pysnark/files/5457407/Archive.zip)

**Comment by stechu** [comment]
@meilof thanks for your reply.
update: I followed the 27 steps in snarkjs readme, it works fine.
Can I know which command to run your attached json files? I get the following no verification key error when run
`snarkjs verify`.

```
snarkjs verify                                                   
[ERROR] snarkJS: Error: ENOENT: no such file or directory, open 'verification_key.json'
    at Object.openSync (fs.js:465:3)
    at Object.readFileSync (fs.js:368:35)
    at Object.groth16Verify$1 [as action] (/usr/local/lib/node_modules/snarkjs/build/cli.cjs:6892:64)
    at clProcessor (/usr/local/lib/node_modules/snarkjs/build/cli.cjs:1264:31)
    at Object.<anonymous> (/usr/local/lib/node_modules/snarkjs/build/cli.cjs:6680:1)
    at Module._compile (internal/modules/cjs/loader.js:1251:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1272:10)
    at Module.load (internal/modules/cjs/loader.js:1100:32)
    at Function.Module._load (internal/modules/cjs/loader.js:962:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: 'verification_key.json'
}
```

**Comment by meilof** [comment]
Sorry, I uploaded the wrong files. Should have tested. Here's the three files generated by pysnark that you need in order to run " snarkjs verify":

[proof.zip](https://github.com/meilof/pysnark/files/5468733/proof.zip)

**Comment by stechu** [comment]
I still get the same error. 
```
⋊> ~/P/p/proof on master ⨯ snarkjs verify                                                      
[ERROR] snarkJS: TypeError: Cannot read property 'toUpperCase' of undefined
    at normalizeName (/usr/local/lib/node_modules/snarkjs/build/cli.cjs:1703:18)
    at getCurveFromName (/usr/local/lib/node_modules/snarkjs/build/cli.cjs:1692:22)
    at groth16Verify (/usr/local/lib/node_modules/snarkjs/build/cli.cjs:6342:25)
    at Object.groth16Verify$1 [as action] (/usr/local/lib/node_modules/snarkjs/build/cli.cjs:6898:27)
    at clProcessor (/usr/local/lib/node_modules/snarkjs/build/cli.cjs:1264:31)
    at Object.<anonymous> (/usr/local/lib/node_modules/snarkjs/build/cli.cjs:6680:1)
    at Module._compile (internal/modules/cjs/loader.js:1251:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1272:10)
    at Module.load (internal/modules/cjs/loader.js:1100:32)
    at Function.Module._load (internal/modules/cjs/loader.js:962:14)
⋊> ~/P/p/proof on master ⨯ snarkjs --version                                                   
snarkjs@0.3.44
```
It appears that there are some changes in `snarkjs`. For example, `snarkjs setup` is no longer available.

**Comment by meilof** [comment]
Ok, then I guess there must be a problem in your install of snarkjs?

Op za 31 okt. 2020 08:58 schreef Shumo Chu <notifications@github.com>:

**Comment by stechu** [comment]
@meilof I dig a bit deeper, here is what I found:

`snarkjs` now requires the verification_key.json has a field named `curve`. 

From https://github.com/iden3/snarkjs/blob/master/build/cli.cjs#L6342
```
async function groth16Verify(vk_verifier, publicSignals, proof, logger) {
/*
    let cpub = vk_verifier.IC[0];
    for (let s= 0; s< vk_verifier.nPublic; s++) {
        cpub  = G1.add( cpub, G1.timesScalar( vk_verifier.IC[s+1], publicSignals[s]));
    }
*/

    vk_verifier = unstringifyBigInts(vk_verifier);
    proof = unstringifyBigInts(proof);
    publicSignals = unstringifyBigInts(publicSignals);

    const curve = await getCurveFromName(vk_verifier.curve);
```
This `vk_verifier` is deserialized from the `verification_key.json` (https://github.com/iden3/snarkjs/blob/master/build/cli.cjs#L6886):
```
async function groth16Verify$1(params, options) {

    const verificationKeyName = params[0] || "verification_key.json";
    const publicName = params[1] || "public.json";
    const proofName = params[2] || "proof.json";

    const verificationKey = unstringifyBigInts$1(JSON.parse(fs.readFileSync(verificationKeyName, "utf8")));
    const pub = unstringifyBigInts$1(JSON.parse(fs.readFileSync(publicName, "utf8")));
    const proof = unstringifyBigInts$1(JSON.parse(fs.readFileSync(proofName, "utf8")));

```
Can you make sure you are indeed running `snarkjs@0.3.44`. You should run into the same problem since the `verification_key.json` doesn't contain a `curve` field.

**Comment by stechu** [comment]
I also noticed that `snarkjs` interface seems to have been completely changed, here is a valid verification key:

```
{
 "protocol": "groth16",
 "curve": "bn128",
 "nPublic": 1,
 "vk_alpha_1": [
  "1157632722168159680441307770233945610993467899582299993886018358117665501926",
  "4588585661318861833261873390908511518403506380785788579668849741802940173387",
  "1"
 ],
 "vk_beta_2": [
  [
   "2880023285305232823024763751554822865570912896459250606872190639975422424731",
   "3108048810281676896890755905867030138490433927323840296629728702193128529632"
  ],
  [
   "9773011907128067163595824890436696261333118973658776627706768966199385523592",
   "3085351526525147691274538395602042519755297564389942460334300228037614208119"
  ],
  [
   "1",
   "0"
  ]
 ],
 "vk_gamma_2": [
  [
   "10857046999023057135944570762232829481370756359578518086990519993285655852781",
   "11559732032986387107991004021392285783925812861821192530917403151452391805634"
  ],
  [
   "8495653923123431417604973247489272438418190587263600148770280649306958101930",
   "4082367875863433681332203403145435568316851327593401208105741076214120093531"
  ],
  [
   "1",
   "0"
  ]
 ],
 "vk_delta_2": [
  [
   "599747333434690520889063519888135093027139759197797741072614139750407863820",
   "18004823571093791676230908004276982243729528217640054483804943162598237148034"
  ],
  [
   "8334794998794280914201127107563574739027144714143063910152746599133098479704",
   "8613482110385447220851683034871026435356317004841830883416470658744785300199"
  ],
  [
   "1",
   "0"
  ]
 ],
 "vk_alphabeta_12": [
  [
   [
    "12310403343480132955264289564603431265619946951381757661594661267440936821409",
    "999571828926229217078890255558394129401023303072999503792089304621644982143"
   ],
   [
    "5685309382698167806022839927630691984386515738050478953844381223035123851478",
    "15369534520284419821464748771381009993697297209434500014568517946427206804903"
   ],
   [
    "18063522485794895570348167485372378300725198693257408522332303427539789469542",
    "3906874605071603096396495135232276381088748356485397398579237886763799952439"
   ]
  ],
  [
   [
    "549175155983165727702387443482905858292201890580270269597089924791938345199",
    "7719550220989145875688629483720820166922724148671096644406427734883250186839"
   ],
   [
    "8546013100531934616882040068207846425315965228592028586141661087040575390769",
    "12385209057369857118328040246948519990104632474235035230478919945249675786858"
   ],
   [
    "8976538069518850151571810728431169672430001065464358053146512093716570765696",
    "16452964893193925582101626911330940496889024270989097632854897594548292744554"
   ]
  ]
 ],
 "IC": [
  [
   "19271802233749997317290177421911730722650573646336863540112377125989855558164",
   "948862361641680482492320767709906706742620037452353144060041728172515956021",
   "1"
  ],
  [
   "15397845347208263368984619907430145495884972784456650000506038618214493527851",
   "207779778764966463233596390754714823041393004729723890134480350444750430503",
   "1"
  ]
 ]
}
```

**Comment by meilof** [comment]
OK, now I see the problem. I will see whether I can have a look in the coming days!

**Comment by stechu** [comment]
@meilof thanks!

**Comment by meilof** [comment]
OK, I think I fixed the problem. Apparently snarkjs does not support the "traditional" Pinocchio zk-SNARK anymore, only the newer Groth16 scheme. And they renamed a few of the fields. 

So you need to get the latest pysnark from SVN (`pip3 install git+https://github.com/meilof/pysnark`), then remove the key material that exists in the examples folder (`rm pysnark_* *.json`), and then do the following to use Groth16-type proofs:

``PYSNARK_BACKEND=libsnarkgg python3 cube.py 33``
``python3 -m pysnark.libsnark.tosnarkjsgg``
``snarkjs verify``

Please let me know if this works for you too!

**Comment by stechu** [comment]
It works for me as well. Thanks fro the fix!
