### ISSUE TITLE
bench.py fails

### ISSUE THREAD

**Issue by utgarda** [meilof/pysnark#8]
Thanks for PySNARK !

Can't run `bench.py` out of the box:
```
➜  examples git:(master) git rev-parse HEAD
607094fa73c151a123a4c82eb92a8802d3ee38b7

➜  examples git:(master) python --version      
Python 3.9.1

➜  examples git:(master) pip show pysnark                                                 
Name: PySNARK
Version: 0.3.1
Summary: Python zk-SNARK execution environment
Home-page: https://github.com/meilof/pysnark
Location: /.local/lib/python3.9/site-packages

➜  examples git:(master) python cube.py 3
The cube of 3 is 27
*** Trying to read pysnark_ek
*** PySNARK: generating proof pysnark_log (sat=True, #io=2, #witness=2, #constraint=3)
*** Public inputs: 3 27
*** Verification status: True

➜  examples git:(master) python bench.py 
Traceback (most recent call last):
  File "/devenv/crypto/zk/meilof/pysnark/examples/bench.py", line 67, in <module>
    print("<, <=, >, >=              ", several([benchmark_lin_bl(lambda:LinComb.ZERO<LinComb.ZERO),
  File "/devenv/crypto/zk/meilof/pysnark/examples/bench.py", line 50, in benchmark_lin_bl
    op4 = count_ops(guarded(LinComb.ONE)(fn))
  File "/devenv/crypto/zk/meilof/pysnark/examples/bench.py", line 15, in count_ops
    benchmark(callback)(fn)()
  File "/.local/lib/python3.9/site-packages/pysnark/runtime.py", line 81, in __benchmark
    ret = fn(*args, **kwargs)
  File "/.local/lib/python3.9/site-packages/pysnark/runtime.py", line 128, in __guarded
    bak = enable_guard(cond)
NameError: name 'enable_guard' is not defined
*** Script returned with error, skipping proof generation
```

**Comment by meilof** [comment]
Fixed, thanks for reporting!
